"""Add review module Attempt #3

Revision ID: 3b774c8de0bb
Revises: 5ee312f2459e
Create Date: 2026-01-03 00:03:30.235155

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3b774c8de0bb'
down_revision: Union[str, Sequence[str], None] = '5ee312f2459e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
