"""Add review module Attempt #2

Revision ID: 5ee312f2459e
Revises: ff057f8ab103
Create Date: 2026-01-03 00:02:32.016364

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5ee312f2459e'
down_revision: Union[str, Sequence[str], None] = 'ff057f8ab103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
